[package]
name = "yeokcham-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "yeokcham"
path = "src/main.rs"

[features]
default = []

[dependencies]
clap.workspace = true
crossterm.workspace = true
minicbor.workspace = true
sha2.workspace = true
thiserror.workspace = true
yeokcham-core = { path = "../yeokcham-core" }
yeokcham-daemon = { path = "../yeokcham-daemon" }
yeokcham-protocol = { path = "../yeokcham-protocol" }

[lints]
workspace = true
