// @generated by `cargo run --manifest-path app/src-tauri/Cargo.toml --bin export-bindings`

export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

export type Decision = "allow" | "deny";

export type ClientScope = "full" | "read-only";

export type ApprovalRequestBody = { protocol_version: string | null, machine_id: string | null, session_id: string | null, agent: string, tool: string, input: JsonValue, cwd: string, metadata: JsonValue | null, };

export type Approval = { protocol_version: string, approval_id: string, machine_id: string, session_id: string, agent: string, tool: string, input: JsonValue, cwd: string, metadata: JsonValue | null, decision: Decision | null, updatedInput: JsonValue | null, reason: string | null, decided_by: string | null, created_at: number, decided_at: number | null, };

export type ApprovalDecisionBody = { decision: Decision, updatedInput: JsonValue | null, reason: string | null, by: string | null, };

export type ApprovalDecisionResponse = { protocol_version: string, approval_id: string, decision: Decision, updatedInput: JsonValue | null, reason: string | null, };

export type AcpPromptBody = { protocol_version: string | null, cwd: string, prompt: string, resumeSessionId: string | null, };

export type AcpPromptResponse = { protocol_version: string, sessionId: string, stopReason: string | null, };

export type RunEvent = { id: number, protocol_version: string, machine_id: string, session_id: string, kind: string, payload: JsonValue, ts: number, };

export type RunEventBody = { protocol_version: string | null, machine_id: string | null, session_id: string, kind: string, timestamp: string | null, payload: JsonValue, };

export type DesktopCommandBlock = { id: string, protocol_version: string | null, sessionId: string, workspaceId: string, agent: string, command: string, cwd: string, startedAt: number, endedAt: number | null, exitCode: number | null, status: string, outputPreview: string, previewUrl: string | null, changedFiles: Array<string>, attention: string | null, source: string | null, };

export type PtyOutputBody = { protocol_version: string | null, machine_id: string | null, session_id: string, data: string, };

export type PaneSendTextBody = { protocol_version: string | null, text: string, sendEnter: boolean, confirmed: boolean, };

export type PaneSendKeysBody = { protocol_version: string | null, preset: string, confirmed: boolean, };

export type PaneRunBody = { protocol_version: string | null, command: string, confirmed: boolean, };

export type PaneSendResponse = { ok: boolean, protocol_version: string, paneId: string, sessionId: string, bytes: number, auditId: string, trustMode: string, requiresConfirmation: boolean, destructive: boolean, preset: string | null, };

export type PaneTarget = { paneId: string, sessionId: string, label: string, agent: string | null, workspaceId: string | null, cwd: string | null, status: string, trustMode: string, };

export type PaneTargetsResponse = { protocol_version: string, targets: Array<PaneTarget>, };

export type DesktopNamedRef = { id: string, name: string, };

export type DesktopSessionSnapshot = { id: string, title: string, agent: string, workspaceId: string, cwd: string | null, status: string, attention: string, previewUrl: string | null, commandBlockCount: number | null, lastCommandBlockId: string | null, remote: JsonValue | null, };

export type DesktopSnapshotBody = { protocol_version: string | null, sessions: Array<DesktopSessionSnapshot>, arrangements: Array<DesktopNamedRef>, updatedAt: number | null, };

export type DesktopSessionLaunchBody = { protocol_version: string | null, agent: string | null, workspace: string, prompt: string | null, cwd: string | null, worktreeStrategy: string | null, };

export type DesktopRemoteSshBody = { protocol_version: string | null, target: string, workspace: string, cwd: string | null, name: string | null, keybindings: string | null, };

export type DesktopWorktreeOpenBody = { protocol_version: string | null, path: string, agent: string | null, prompt: string | null, };

export type CheckpointRecord = { approvalId: string, sessionId: string, cwd: string, preRef: string, postRef: string | null, createdAt: number, updatedAt: number, error: string | null, };

export type CheckpointDiffFile = { path: string, oldLabel: string, newLabel: string, oldText: string | null, newText: string | null, binary: boolean, };

export type CheckpointDiff = { protocolVersion: string, approvalId: string, preRef: string, postRef: string | null, files: Array<CheckpointDiffFile>, };

export type CheckpointRestoreBody = { protocol_version: string | null, };

export type CheckpointPruneBody = { protocol_version: string | null, };

export type CheckpointPruneResponse = { ok: boolean, protocolVersion: string, recordsDeleted: number, refsAttempted: number, refsDeleted: number, refsFailed: number, };

export type DesktopSessionInputBody = { protocol_version: string | null, text: string, };

export type DesktopPaneSplitBody = { protocol_version: string | null, direction: string, };

export type DesktopCommandResponse = { ok: boolean, protocolVersion: string, commandId: string, };

export type PairRequest = { deviceLabel: string, pushSubscription: JsonValue | null, };

export type PairResponse = { protocol_version: string, deviceId: string, machineId: string, scope: ClientScope, };

export type ServerMessage = { "type": "approval-pending", protocol_version: string, approval_id: string, machine_id: string, session_id: string, agent: string, tool: string, input: JsonValue, cwd: string, metadata: JsonValue | null, created_at: number, expires_at: number | null, } | { "type": "approval-resolved", protocol_version: string, approval_id: string, machine_id: string, decision: Decision, by: string | null, reason: string | null, } | { "type": "run-event", protocol_version: string, machine_id: string, session_id: string, kind: string, payload: JsonValue, } | { "type": "pty-output", protocol_version: string, machine_id: string, session_id: string, data: string, } | { "type": "desktop-command", protocol_version: string, machine_id: string, command_id: string, kind: string, payload: JsonValue, } | { "type": "ping", protocol_version: string, machine_id: string, };
