// @generated by `cargo run --manifest-path app/src-tauri/Cargo.toml --bin export-bindings`

export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

export type Decision = "allow" | "deny";

export type ClientScope = "full" | "read-only";

export type ApprovalRequestBody = { protocol_version: string | null, machine_id: string | null, session_id: string | null, agent: string, tool: string, input: JsonValue, cwd: string, metadata: JsonValue | null, };

export type Approval = { protocol_version: string, approval_id: string, machine_id: string, session_id: string, agent: string, tool: string, input: JsonValue, cwd: string, metadata: JsonValue | null, decision: Decision | null, updatedInput: JsonValue | null, reason: string | null, decided_by: string | null, created_at: number, decided_at: number | null, };

export type ApprovalDecisionBody = { decision: Decision, updatedInput: JsonValue | null, reason: string | null, by: string | null, };

export type ApprovalDecisionResponse = { protocol_version: string, approval_id: string, decision: Decision, updatedInput: JsonValue | null, reason: string | null, };

export type AcpPromptBody = { protocol_version: string | null, cwd: string, prompt: string, resumeSessionId: string | null, };

export type AcpProviderResume = { command: string, args: Array<string>, source: string | null, };

export type AcpProviderSession = { agent: string, providerSessionId: string | null, conversationId: string | null, resume: AcpProviderResume | null, updatedAt: number, };

export type AcpPromptResponse = { protocol_version: string, sessionId: string, paneId: string, agent: string, cwd: string, providerSessionId: string | null, conversationId: string | null, provider: AcpProviderSession, resumed: boolean, reattached: boolean, stopReason: string | null, };

export type RuntimeConfig = { approvalTimeoutSecs: number, ptyRingLimit: number, checkpointingEnabled: boolean, checkpointMaxRecords: number, checkpointMaxAgeDays: number, };

export type AdapterRuntimeConfig = { transport: string, acpCommand: string, acpArgs: Array<string>, };

export type AdapterRuntimeConfigs = { claude: AdapterRuntimeConfig, hermes: AdapterRuntimeConfig, };

export type PolicyValidationStatus = { path: string, exists: boolean, ruleCount: number, ok: boolean, error: string | null, };

export type ConfigStatusResponse = { ok: boolean, protocolVersion: string, path: string, exists: boolean, runtimeConfig: RuntimeConfig, fileRuntimeConfig: RuntimeConfig, adapters: AdapterRuntimeConfigs, reloadableFields: Array<string>, restartRequiredFields: Array<string>, clientManagedFields: Array<string>, policyValidation: PolicyValidationStatus, };

export type TransportStatus = { "state": "stopped" } | { "state": "starting" } | { "state": "running", url: string | null, fingerprint: string | null, } | { "state": "failed", message: string, };

export type TransportSnapshot = { name: string, label: string, requiresExternalDep: string | null, enabled: boolean, status: TransportStatus, url: string | null, fingerprint: string | null, };

export type ShellMode = "auto" | "login" | "non_login";

export type TrustMode = "approval-required" | "full-access";

export type RemoteKeybindingPolicy = "local" | "remote";

export type RemoteBootstrapStatus = "unknown" | "ready" | "failed";

export type RemoteDaemonStatus = "unknown" | "running" | "failed";

export type RemoteSessionMetadata = { kind: string, target: string, user?: string, host: string, port?: number, remoteCwd?: string, keybindingPolicy: RemoteKeybindingPolicy, bootstrapStatus?: RemoteBootstrapStatus, helperPath?: string, helperVersion?: string, stagingDir?: string, lastBootstrapAt?: number, daemonStatus?: RemoteDaemonStatus, daemonPid?: number, daemonLogPath?: string, daemonRunDir?: string, lastDaemonStartAt?: number, };

export type PtySpawnRequest = { command: string, args: Array<string>, cwd: string | null, env: Array<[string, string]>, shellMode: ShellMode, rows: number, cols: number, name?: string, agent?: string, workspaceId?: string, safeMode: boolean, trustMode: TrustMode, title?: string, remote?: RemoteSessionMetadata, };

export type PtyWireEvent = { "type": "data", data: string, offset: number, } | { "type": "exit", code: number, signal: string | null, } | { "type": "notification", source: string, title: string, body: string | null, urgency: string | null, };

export type PtyReplaySnapshot = { data: string, startOffset: number, endOffset: number, };

export type PtySessionRestart = { command: string, args: Array<string>, cwd: string | null, env: Array<[string, string]>, shellMode: ShellMode, safeMode: boolean, trustMode: TrustMode, remote?: RemoteSessionMetadata, };

export type PtyProviderResume = { command: string, args: Array<string>, source: string | null, };

export type PtyProviderSession = { agent: string, providerSessionId: string | null, conversationId: string | null, resume: PtyProviderResume | null, updatedAt: number, };

export type PtySessionMetadata = { id: string, paneId: string, name: string | null, agent: string | null, workspaceId: string | null, safeMode: boolean, trustMode: TrustMode, cwd: string | null, title: string | null, status: string, lifecycle: string, rows: number, cols: number, createdAt: number, updatedAt: number, processId: number | null, stoppedAt: number | null, exitCode: number | null, exitSignal: string | null, restart: PtySessionRestart | null, provider: PtyProviderSession | null, remote: RemoteSessionMetadata | null, };

export type PtyAttachResult = { ok: boolean, attached: boolean, relaunched: boolean, previousSessionId: string | null, id: string, sessionId: string, paneId: string, session: PtySessionMetadata, };

export type RemoteSshBootstrapRequest = { target: string, user?: string, host: string, port?: number, remoteCwd?: string, sshCommand?: string, helperPath?: string, stagingDir?: string, };

export type RemoteSshBootstrapResult = { ok: boolean, target: string, helperPath: string, helperVersion: string, stagingDir: string, bootstrappedAt: number, stdout: string, stderr: string, };

export type RemoteSshDaemonRequest = { target: string, user?: string, host: string, port?: number, remoteCwd?: string, sshCommand?: string, helperPath?: string, runDir?: string, };

export type RemoteSshDaemonResult = { ok: boolean, target: string, helperPath: string, runDir: string, pid: number, status: string, logPath: string, startedAt: number, stdout: string, stderr: string, };

export type RemoteSshStageFileRequest = { target: string, user?: string, host: string, port?: number, remoteCwd?: string, sshCommand?: string, stagingDir?: string, filename: string, data: Array<number>, };

export type RemoteSshStageFileResult = { ok: boolean, remotePath: string, bytes: number, stdout: string, stderr: string, };

export type RunEvent = { id: number, protocol_version: string, machine_id: string, session_id: string, kind: string, payload: JsonValue, ts: number, };

export type RunEventBody = { protocol_version: string | null, machine_id: string | null, session_id: string, kind: string, timestamp: string | null, payload: JsonValue, };

export type DesktopCommandBlock = { id: string, protocol_version: string | null, sessionId: string, workspaceId: string, agent: string, command: string, cwd: string, startedAt: number, endedAt: number | null, exitCode: number | null, status: string, outputPreview: string, previewUrl: string | null, changedFiles: Array<string>, attention: string | null, source: string | null, };

export type PtyOutputBody = { protocol_version: string | null, machine_id: string | null, session_id: string, data: string, };

export type PaneSendTextBody = { protocol_version: string | null, text: string, sendEnter: boolean, confirmed: boolean, };

export type PaneSendKeysBody = { protocol_version: string | null, preset: string, confirmed: boolean, };

export type PaneRunBody = { protocol_version: string | null, command: string, confirmed: boolean, };

export type PaneSendResponse = { ok: boolean, protocol_version: string, paneId: string, sessionId: string, bytes: number, auditId: string, trustMode: string, requiresConfirmation: boolean, destructive: boolean, preset: string | null, };

export type PaneTarget = { paneId: string, sessionId: string, label: string, agent: string | null, workspaceId: string | null, cwd: string | null, status: string, trustMode: string, };

export type PaneTargetsResponse = { protocol_version: string, targets: Array<PaneTarget>, };

export type DesktopNamedRef = { id: string, name: string, };

export type DesktopSessionSnapshot = { id: string, title: string, agent: string, workspaceId: string, cwd: string | null, status: string, attention: string, previewUrl: string | null, commandBlockCount: number | null, lastCommandBlockId: string | null, remote: JsonValue | null, };

export type DesktopSnapshotBody = { protocol_version: string | null, sessions: Array<DesktopSessionSnapshot>, arrangements: Array<DesktopNamedRef>, updatedAt: number | null, };

export type DesktopSessionLaunchBody = { protocol_version: string | null, agent: string | null, workspace: string, prompt: string | null, cwd: string | null, worktreeStrategy: string | null, };

export type DesktopRemoteSshBody = { protocol_version: string | null, target: string, workspace: string, cwd: string | null, name: string | null, keybindings: string | null, };

export type DesktopWorktreeOpenBody = { protocol_version: string | null, path: string, agent: string | null, prompt: string | null, };

export type CheckpointRecord = { approvalId: string, sessionId: string, cwd: string, preRef: string, postRef: string | null, createdAt: number, updatedAt: number, error: string | null, };

export type CheckpointDiffFile = { path: string, oldLabel: string, newLabel: string, oldText: string | null, newText: string | null, binary: boolean, };

export type CheckpointDiff = { protocolVersion: string, approvalId: string, preRef: string, postRef: string | null, files: Array<CheckpointDiffFile>, };

export type CheckpointRestoreBody = { protocol_version: string | null, };

export type CheckpointPruneBody = { protocol_version: string | null, };

export type CheckpointPruneResponse = { ok: boolean, protocolVersion: string, recordsDeleted: number, refsAttempted: number, refsDeleted: number, refsFailed: number, };

export type DesktopSessionInputBody = { protocol_version: string | null, text: string, };

export type DesktopPaneSplitBody = { protocol_version: string | null, direction: string, };

export type DesktopCommandResponse = { ok: boolean, protocolVersion: string, commandId: string, };

export type PairRequest = { deviceLabel: string, pushSubscription: JsonValue | null, };

export type PairResponse = { protocol_version: string, deviceId: string, machineId: string, scope: ClientScope, };

export type ServerMessage = { "type": "approval-pending", protocol_version: string, approval_id: string, machine_id: string, session_id: string, agent: string, tool: string, input: JsonValue, cwd: string, metadata: JsonValue | null, created_at: number, expires_at: number | null, } | { "type": "approval-resolved", protocol_version: string, approval_id: string, machine_id: string, decision: Decision, by: string | null, reason: string | null, } | { "type": "run-event", protocol_version: string, machine_id: string, session_id: string, kind: string, payload: JsonValue, } | { "type": "pty-output", protocol_version: string, machine_id: string, session_id: string, data: string, } | { "type": "desktop-command", protocol_version: string, machine_id: string, command_id: string, kind: string, payload: JsonValue, } | { "type": "ping", protocol_version: string, machine_id: string, };
