// @generated by `cargo run --manifest-path app/src-tauri/Cargo.toml --bin export-bindings`

type Decision = "allow" | "deny";

type ClientScope = "full" | "read-only";

type ApprovalRequestBody = { protocol_version: string | null, machine_id: string | null, session_id: string | null, agent: string, tool: string, input: JsonValue, cwd: string, metadata: JsonValue | null, };

type Approval = { protocol_version: string, approval_id: string, machine_id: string, session_id: string, agent: string, tool: string, input: JsonValue, cwd: string, metadata: JsonValue | null, decision: Decision | null, updatedInput: JsonValue | null, reason: string | null, decided_by: string | null, created_at: bigint, decided_at: bigint | null, };

type ApprovalDecisionBody = { decision: Decision, updatedInput: JsonValue | null, reason: string | null, by: string | null, };

type ApprovalDecisionResponse = { protocol_version: string, approval_id: string, decision: Decision, updatedInput: JsonValue | null, reason: string | null, };

type RunEvent = { id: bigint, protocol_version: string, machine_id: string, session_id: string, kind: string, payload: JsonValue, ts: bigint, };

type RunEventBody = { protocol_version: string | null, machine_id: string | null, session_id: string, kind: string, timestamp: string | null, payload: JsonValue, };

type ProviderEventBody = { protocol_version: string | null, machine_id: string | null, session_id: string | null, provider_session_id: string | null, conversation_id: string | null, event: string | null, status: string | null, cwd: string | null, tool: string | null, input: JsonValue, raw: JsonValue | null, };

type DesktopCommandBlock = { id: string, protocol_version: string | null, sessionId: string, workspaceId: string, agent: string, command: string, cwd: string, startedAt: bigint, endedAt: bigint | null, exitCode: bigint | null, status: string, outputPreview: string, previewUrl: string | null, changedFiles: Array<string>, attention: string | null, source: string | null, };

type PtyOutputBody = { protocol_version: string | null, machine_id: string | null, session_id: string, data: string, };

type DesktopNamedRef = { id: string, name: string, };

type DesktopSessionSnapshot = { id: string, title: string, agent: string, workspaceId: string, cwd: string | null, status: string, attention: string, previewUrl: string | null, commandBlockCount: number | null, lastCommandBlockId: string | null, remote: JsonValue | null, };

type DesktopSnapshotBody = { protocol_version: string | null, sessions: Array<DesktopSessionSnapshot>, arrangements: Array<DesktopNamedRef>, updatedAt: bigint | null, };

type DesktopSessionLaunchBody = { protocol_version: string | null, agent: string | null, workspace: string, prompt: string | null, cwd: string | null, };

type DesktopRemoteSshBody = { protocol_version: string | null, target: string, workspace: string, cwd: string | null, name: string | null, keybindings: string | null, };

type DesktopWorktreeOpenBody = { protocol_version: string | null, path: string, agent: string | null, prompt: string | null, };

type DesktopSessionInputBody = { protocol_version: string | null, text: string, };

type DesktopPaneSplitBody = { protocol_version: string | null, direction: string, };

type DesktopCommandResponse = { ok: boolean, protocolVersion: string, commandId: string, };

type PairRequest = { deviceLabel: string, pushSubscription: JsonValue | null, };

type PairResponse = { protocol_version: string, deviceId: string, machineId: string, scope: ClientScope, };

type ServerMessage = { "type": "approval-pending", protocol_version: string, approval_id: string, machine_id: string, session_id: string, agent: string, tool: string, input: JsonValue, cwd: string, metadata: JsonValue | null, created_at: bigint, expires_at: bigint | null, } | { "type": "approval-resolved", protocol_version: string, approval_id: string, machine_id: string, decision: Decision, by: string | null, reason: string | null, } | { "type": "run-event", protocol_version: string, machine_id: string, session_id: string, kind: string, payload: JsonValue, } | { "type": "pty-output", protocol_version: string, machine_id: string, session_id: string, data: string, } | { "type": "desktop-command", protocol_version: string, machine_id: string, command_id: string, kind: string, payload: JsonValue, } | { "type": "ping", protocol_version: string, machine_id: string, };
