# SwiftLint Configuration for Onibi

excluded:
  - .build
  - build
  - DerivedData
  - Packages

disabled_rules:
  - trailing_comma
  - trailing_whitespace
  - opening_brace
  - identifier_name
  - nesting
  - type_body_length
  - file_length
  - function_body_length
  - cyclomatic_complexity
  - function_parameter_count
  - large_tuple
  - line_length
  - todo
  - redundant_string_enum_value # Intentional for JSON serialization
  - multiple_closures_with_trailing_closure # SwiftUI patterns often use this
  - for_where # Code readability preference

opt_in_rules:
  - fatal_error_message
  - first_where
  - private_over_fileprivate
  - sorted_first_last
  - toggle_bool
  - unused_declaration

# Analyzer rules
analyzer_rules:
  - unused_import

# Rule configurations
type_name:
  min_length: 2
  max_length: 50

warning_threshold: 50
