# SwiftLint Configuration for Onibi

excluded:
  - .build
  - build
  - DerivedData
  - Packages

disabled_rules:
  - trailing_comma
  - trailing_whitespace
  - opening_brace
  - identifier_name
  - nesting
  - type_body_length
  - file_length
  - function_body_length
  - cyclomatic_complexity
  - function_parameter_count
  - large_tuple
  - line_length
  - todo

opt_in_rules:
  - empty_count
  - fatal_error_message
  - first_where
  - modifier_order
  - private_over_fileprivate
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - unused_declaration

# Analyzer rules
analyzer_rules:
  - unused_import

# Rule configurations
type_name:
  min_length: 2
  max_length: 50

warning_threshold: 50
