[package]
name = "arachne-rust-integrator-example"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
thiserror.workspace = true
tokio.workspace = true
arachne-core = { path = "../../crates/arachne-core" }
arachne-sdk = { path = "../../crates/arachne-sdk" }

[lints]
workspace = true
