// Generated by scripts/generate-pi-protocol-types.mjs. Do not edit by hand.

export type PiEnvelopeSender = "pi" | "cp";

export type JsonPrimitive = string | number | boolean | null;
export type JsonValue =
  | JsonPrimitive
  | readonly JsonValue[]
  | { readonly [key: string]: JsonValue };
export type JsonRecord = { readonly [key: string]: JsonValue };

export interface PiWireEnvelope {
  readonly msg_id: string;
  readonly ts: string;
  readonly sender: PiEnvelopeSender;
  readonly kind: string;
  readonly payload: JsonRecord;
  readonly sig: string;
}

export const piWireEnvelopeSchemaId =
  "https://kelpclaw.dev/schemas/pi/envelope.v1.schema.json" as const;
