apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-labeled-client-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: relay
      app.kubernetes.io/name: arachne
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              arachne.io/relay-client: "true"
      ports:
        - port: 50051
          protocol: TCP
