apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: arachne-relay
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: relay
      app.kubernetes.io/name: arachne
