apiVersion: v1
kind: Service
metadata:
  name: arachne-relay-headless
  labels:
    app.kubernetes.io/component: relay
    app.kubernetes.io/name: arachne
spec:
  clusterIP: None
  ports:
    - name: grpc
      port: 50051
      protocol: TCP
      targetPort: grpc
  selector:
    app.kubernetes.io/component: relay
    app.kubernetes.io/name: arachne
---
apiVersion: v1
kind: Service
metadata:
  name: arachne-relay
  labels:
    app.kubernetes.io/component: relay
    app.kubernetes.io/name: arachne
spec:
  ports:
    - name: grpc
      port: 50051
      protocol: TCP
      targetPort: grpc
  selector:
    app.kubernetes.io/component: relay
    app.kubernetes.io/name: arachne
