[package]
name = "yeokcham-relay-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false
build = "build.rs"

[features]
default = []

[dependencies]
prost.workspace = true
tonic.workspace = true
tonic-prost.workspace = true

[build-dependencies]
tonic-prost-build.workspace = true

[dev-dependencies]
tokio.workspace = true
tokio-stream.workspace = true

[lints]
workspace = true
