[package]
name = "yeokcham-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []

[dependencies]
argon2.workspace = true
chacha20poly1305.workspace = true
getrandom.workspace = true
hkdf.workspace = true
minicbor.workspace = true
sha2.workspace = true
subtle.workspace = true
thiserror.workspace = true
yeokcham-core = { path = "../yeokcham-core" }
zeroize.workspace = true

[dev-dependencies]
criterion.workspace = true
proptest.workspace = true

[[bench]]
name = "wire"
harness = false

[lints]
workspace = true
