package cli

import (
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/gongahkia/onibi/internal/config"
	"github.com/gongahkia/onibi/internal/web"
	"github.com/spf13/cobra"
)

type phoneSetupState struct {
	Transport    string
	MobileConfig string
	CACert       string
	CertReady    bool
}

func needsLocalPhoneTrust(transport string) bool {
	switch strings.ToLower(strings.TrimSpace(transport)) {
	case "lan", "tailscale-private", "wireguard", "zerotier", "auto":
		return true
	default:
		return false
	}
}

func printPhoneSetupGuide(cmd *cobra.Command, state phoneSetupState) {
	writePhoneSetupGuide(cmd.OutOrStdout(), state)
}

func writePhoneSetupGuide(out io.Writer, state phoneSetupState) {
	transport := strings.ToLower(strings.TrimSpace(state.Transport))
	mode := normalizePairTransport(transport)
	fmt.Fprintln(out, "Phone setup")
	if !needsLocalPhoneTrust(transport) {
		fmt.Fprintln(out, "1. Keep Onibi running and scan the pairing QR on your phone.")
		fmt.Fprintln(out, "2. Add the paired cockpit to Home Screen or install it as a web app.")
		return
	}
	if !state.CertReady {
		fmt.Fprintf(out, "1. Run `onibi up --transport=%s` to generate local HTTPS trust files and a fresh pairing QR.\n", mode)
		fmt.Fprintln(out, "2. Keep that command running; it prints the platform-specific next steps.")
		return
	}
	fmt.Fprintln(out, "1. Transfer the matching trust file from this Mac through a channel you control (private file sync or USB cable); do not download a CA file from the local network.")
	fmt.Fprintln(out, "   iPhone/iPad:", state.MobileConfig)
	fmt.Fprintln(out, "   Android:", state.CACert)
	fmt.Fprintln(out, "2. iPhone/iPad: install the profile, then enable full trust for Onibi local CA in Certificate Trust Settings.")
	fmt.Fprintln(out, "   Android: install the CA certificate from the system Security settings; menu labels vary by device.")
	fmt.Fprintln(out, "3. Scan the new pairing QR, then add the paired cockpit to Home Screen or install it as a web app.")
	fmt.Fprintln(out, "The private CA key stays on this Mac. Trust only the file generated by this Onibi state directory.")
}

func printDoctorPhoneSetup(cmd *cobra.Command, paths config.Paths, transportOverride string) {
	cfg, _, err := config.Load(paths)
	if err != nil {
		return
	}
	transport := strings.TrimSpace(transportOverride)
	if transport == "" {
		transport = cfg.Transport.Mode
	}
	switch strings.ToLower(strings.TrimSpace(transport)) {
	case "telegram", "irc":
		return
	}
	certPaths := web.LocalCertPaths(certDir(paths, cfg))
	_, err = os.Stat(certPaths.MobileConfig)
	printPhoneSetupGuide(cmd, phoneSetupState{
		Transport:    transport,
		MobileConfig: certPaths.MobileConfig,
		CACert:       certPaths.CACert,
		CertReady:    err == nil,
	})
}
