[package]
name = "arachne-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[features]
default = []
experimental-relay-replication = []

[dependencies]
argon2.workspace = true
chacha20poly1305.workspace = true
getrandom.workspace = true
hkdf.workspace = true
minicbor.workspace = true
sha2.workspace = true
sha3.workspace = true
subtle.workspace = true
thiserror.workspace = true
arachne-core = { path = "../arachne-core" }
zeroize.workspace = true

[dev-dependencies]
criterion.workspace = true
proptest.workspace = true

[[bench]]
name = "wire"
harness = false

[lints]
workspace = true
