package browser

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/mxschmitt/playwright-go"
)

const (
	perfectGymFacilityTypeControlSelector  = `div[role="combobox"][aria-label="Facility Type"]`
	perfectGymFacilityTypeSelectedSelector = perfectGymFacilityTypeControlSelector + ` .baf-combobox-selected-item`
	perfectGymFacilityTypeOptionSelector   = `div.baf-dropdown.is-active div.baf-combobox-item`
	perfectGymNextWeekSelector             = `i[aria-label="Next week"]`
	perfectGymSchedulePath                 = "FacilityBookings/FacilityCalendar/GetWeeklySchedule"
)

// PerfectGymScanRequest scopes a read-only scan to a configured PerfectGym
// facility calendar. It contains no booking, cart, checkout, or payment path.
type PerfectGymScanRequest struct {
	AvailabilityURL    string
	FacilityTypeName   string
	SessionStateBase64 string
	PermittedHosts     []string
	Timeout            time.Duration
	EndDate            time.Time
}

// PerfectGymAvailability is one calendar entry before provider-specific
// normalization. The aggregate calendar does not identify a specific court.
type PerfectGymAvailability struct {
	Start  time.Time
	End    time.Time
	Status string
}

// PerfectGymScanner keeps the provider adapter testable without launching
// Chromium. It has no operation capable of selecting or booking a slot.
type PerfectGymScanner interface {
	ScanPerfectGym(context.Context, PerfectGymScanRequest) ([]PerfectGymAvailability, error)
}

// ScanPerfectGym opens a configured availability page, verifies the badminton
// facility type, and reads only the calendar responses generated by advancing
// the displayed week. It never selects a facility, slot, cart, or checkout.
func (client *Playwright) ScanPerfectGym(ctx context.Context, request PerfectGymScanRequest) ([]PerfectGymAvailability, error) {
	if err := validatePerfectGymRequest(request); err != nil {
		return nil, err
	}
	if err := acquire(ctx, client.sem); err != nil {
		return nil, err
	}
	defer func() { <-client.sem }()
	if err := client.start(); err != nil {
		return nil, err
	}

	options, err := contextOptions(request.SessionStateBase64)
	if err != nil {
		return nil, err
	}
	options.TimezoneId = playwright.String("Asia/Singapore")
	browserContext, err := client.browser.NewContext(options)
	if err != nil {
		return nil, fmt.Errorf("create PerfectGym browser context: %w", err)
	}
	defer browserContext.Close()
	page, err := browserContext.NewPage()
	if err != nil {
		return nil, fmt.Errorf("open PerfectGym availability page: %w", err)
	}
	timeout := request.Timeout
	if timeout <= 0 {
		timeout = 25 * time.Second
	}
	page.SetDefaultTimeout(float64(timeout.Milliseconds()))
	page.SetDefaultNavigationTimeout(float64(timeout.Milliseconds()))

	response, err := expectPerfectGymSchedule(page, func() error {
		_, err := page.Goto(request.AvailabilityURL)
		return err
	}, timeout)
	if err != nil {
		return nil, fmt.Errorf("open PerfectGym calendar: %w", err)
	}
	if _, err := page.WaitForSelector(perfectGymFacilityTypeControlSelector); err != nil {
		return nil, fmt.Errorf("wait for PerfectGym facility type: %w", err)
	}
	facilityTypeControl := page.Locator(perfectGymFacilityTypeControlSelector)
	selected, err := page.Locator(perfectGymFacilityTypeSelectedSelector).TextContent()
	if err != nil {
		return nil, fmt.Errorf("read PerfectGym facility type: %w", err)
	}
	if !strings.EqualFold(strings.TrimSpace(selected), request.FacilityTypeName) {
		response, err = expectPerfectGymSchedule(page, func() error {
			if err := facilityTypeControl.Click(); err != nil {
				return err
			}
			return page.Locator(perfectGymFacilityTypeOptionSelector, playwright.PageLocatorOptions{HasText: request.FacilityTypeName}).Click()
		}, timeout)
		if err != nil {
			return nil, fmt.Errorf("select PerfectGym facility type %q: %w", request.FacilityTypeName, err)
		}
	}

	result := []PerfectGymAvailability{}
	for pageNumber := 0; pageNumber < perfectGymMaxPages(request); pageNumber++ {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		entries, canGoForward, err := decodePerfectGymSchedule(response)
		if err != nil {
			return nil, err
		}
		result = append(result, entries...)
		if !canGoForward || perfectGymCovers(entries, request.EndDate) {
			break
		}
		response, err = expectPerfectGymSchedule(page, func() error {
			return page.Locator(perfectGymNextWeekSelector).Click()
		}, timeout)
		if err != nil {
			return nil, fmt.Errorf("advance PerfectGym calendar: %w", err)
		}
	}
	return result, nil
}

func validatePerfectGymRequest(request PerfectGymScanRequest) error {
	if err := validateURL(request.AvailabilityURL, request.PermittedHosts); err != nil {
		return fmt.Errorf("PerfectGym availability URL: %w", err)
	}
	if strings.TrimSpace(request.SessionStateBase64) == "" {
		return errors.New("PerfectGym scan needs an imported browser session")
	}
	if strings.TrimSpace(request.FacilityTypeName) == "" {
		return errors.New("PerfectGym scan needs a facility type name")
	}
	return nil
}

func expectPerfectGymSchedule(page playwright.Page, action func() error, timeout time.Duration) (playwright.Response, error) {
	return page.ExpectResponse(func(response playwright.Response) bool {
		request := response.Request()
		body, err := request.PostData()
		return err == nil && perfectGymScheduleResponseMatches(response.URL(), response.Status(), request.Method(), body)
	}, action, playwright.PageExpectResponseOptions{Timeout: playwright.Float(float64(timeout.Milliseconds()))})
}

// perfectGymScheduleResponseMatches excludes the empty bootstrap calendar call
// and accepts only the facility-scoped calendar response that carries slots.
func perfectGymScheduleResponseMatches(url string, status int, method, body string) bool {
	return status == 200 && method == "POST" && strings.Contains(url, perfectGymSchedulePath) && strings.Contains(body, `"zoneTypeId"`)
}

func perfectGymMaxPages(request PerfectGymScanRequest) int {
	if request.EndDate.IsZero() {
		return 1
	}
	return 6
}

func perfectGymCovers(entries []PerfectGymAvailability, endDate time.Time) bool {
	if endDate.IsZero() {
		return true
	}
	for _, entry := range entries {
		if !entry.Start.Before(endDate) || !entry.End.Before(endDate) {
			return true
		}
	}
	return false
}

type perfectGymSchedule struct {
	CalendarData []struct {
		ClassesPerDay [][]perfectGymSlot `json:"ClassesPerDay"`
	} `json:"CalendarData"`
	PagerData struct {
		CanGoForward bool `json:"CanGoForward"`
	} `json:"PagerData"`
}

type perfectGymSlot struct {
	StartTime string `json:"StartTime"`
	EndTime   string `json:"EndTime"`
	Status    string `json:"Status"`
}

func decodePerfectGymSchedule(response playwright.Response) ([]PerfectGymAvailability, bool, error) {
	body, err := response.Body()
	if err != nil {
		return nil, false, fmt.Errorf("read PerfectGym calendar response: %w", err)
	}
	return parsePerfectGymSchedule(body)
}

func parsePerfectGymSchedule(body []byte) ([]PerfectGymAvailability, bool, error) {
	var payload perfectGymSchedule
	if err := json.Unmarshal(body, &payload); err != nil {
		return nil, false, fmt.Errorf("decode PerfectGym calendar response: %w", err)
	}
	entries := []PerfectGymAvailability{}
	for _, row := range payload.CalendarData {
		for _, day := range row.ClassesPerDay {
			for _, slot := range day {
				start, err := perfectGymTime(slot.StartTime)
				if err != nil {
					return nil, false, fmt.Errorf("parse PerfectGym slot start: %w", err)
				}
				end, err := perfectGymTime(slot.EndTime)
				if err != nil {
					return nil, false, fmt.Errorf("parse PerfectGym slot end: %w", err)
				}
				if !end.After(start) {
					return nil, false, errors.New("PerfectGym slot ends before it starts")
				}
				entries = append(entries, PerfectGymAvailability{Start: start, End: end, Status: strings.TrimSpace(slot.Status)})
			}
		}
	}
	return entries, payload.PagerData.CanGoForward, nil
}

func perfectGymTime(value string) (time.Time, error) {
	value = strings.TrimSpace(value)
	for _, layout := range []string{time.RFC3339Nano, time.RFC3339} {
		if parsed, err := time.Parse(layout, value); err == nil {
			return parsed, nil
		}
	}
	location, err := time.LoadLocation("Asia/Singapore")
	if err != nil {
		location = time.FixedZone("SGT", 8*60*60)
	}
	parsed, err := time.ParseInLocation("2006-01-02T15:04:05", value, location)
	if err != nil {
		return time.Time{}, fmt.Errorf("invalid time %q", value)
	}
	return parsed, nil
}
