[package]
name = "yeokcham-daemon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []

[dependencies]
chacha20poly1305.workspace = true
getrandom.workspace = true
minicbor.workspace = true
rusqlite.workspace = true
thiserror.workspace = true
yeokcham-core = { path = "../yeokcham-core" }
yeokcham-protocol = { path = "../yeokcham-protocol" }
zeroize.workspace = true

[lints]
workspace = true
