[package]
name = "yeokcham-relay"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[features]
default = []

[dependencies]
getrandom.workspace = true
rusqlite.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tonic.workspace = true
yeokcham-core = { path = "../yeokcham-core" }
yeokcham-protocol = { path = "../yeokcham-protocol" }
yeokcham-relay-api = { path = "../yeokcham-relay-api" }
zeroize.workspace = true

[lints]
workspace = true
