[package]
name = "yeokcham-relay"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []

[dependencies]
rusqlite.workspace = true
thiserror.workspace = true
yeokcham-core = { path = "../yeokcham-core" }
yeokcham-protocol = { path = "../yeokcham-protocol" }

[lints]
workspace = true
