[package]
name = "yeokcham-sdk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []

[dependencies]
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
yeokcham-core = { path = "../yeokcham-core" }
yeokcham-daemon = { path = "../yeokcham-daemon" }
yeokcham-protocol = { path = "../yeokcham-protocol" }

[dev-dependencies]
hyper-util.workspace = true
tonic.workspace = true
tower.workspace = true
yeokcham-daemon-api = { path = "../yeokcham-daemon-api" }

[lints]
workspace = true
