use std::{fs, path::PathBuf};

fn workspace_file(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join(name)
}

#[test]
fn pins_toolchain_and_tracks_lockfile() {
    let toolchain = fs::read_to_string(workspace_file("rust-toolchain.toml"))
        .expect("workspace must include rust-toolchain.toml");
    assert!(
        toolchain.contains("channel = \"1.93.0\""),
        "toolchain must use an exact Rust release"
    );
    assert!(
        toolchain.contains("components = [\"clippy\", \"rustfmt\"]"),
        "toolchain must install CI components"
    );
    assert!(
        toolchain.contains("profile = \"minimal\""),
        "toolchain must use the minimal profile"
    );

    let lockfile =
        fs::read_to_string(workspace_file("Cargo.lock")).expect("workspace must track Cargo.lock");
    assert!(
        lockfile.starts_with("# This file is automatically @generated by Cargo."),
        "Cargo.lock must be a Cargo-generated lockfile"
    );
}

#[test]
fn workspace_features_are_explicitly_opt_in() {
    let policy = fs::read_to_string(workspace_file("FEATURES.md"))
        .expect("workspace must document feature policy");
    assert!(policy.contains("default = []"));
    assert!(policy.contains("must be additive"));

    for package in [
        "yeokcham-cli",
        "yeokcham-core",
        "yeokcham-daemon",
        "yeokcham-ffi",
        "yeokcham-protocol",
        "yeokcham-relay",
    ] {
        let manifest = fs::read_to_string(workspace_file(&format!("crates/{package}/Cargo.toml")))
            .expect("workspace crate must include Cargo.toml");
        assert!(
            manifest.contains("[features]\ndefault = []"),
            "{package} must keep all features opt-in"
        );
    }
}
