use std::{fs, path::PathBuf};

fn workspace_file(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join(name)
}

#[test]
fn pins_toolchain_and_tracks_lockfile() {
    let toolchain = fs::read_to_string(workspace_file("rust-toolchain.toml"))
        .expect("workspace must include rust-toolchain.toml");
    assert!(
        toolchain.contains("channel = \"1.93.0\""),
        "toolchain must use an exact Rust release"
    );
    assert!(
        toolchain.contains("components = [\"clippy\", \"rustfmt\"]"),
        "toolchain must install CI components"
    );
    assert!(
        toolchain.contains("profile = \"minimal\""),
        "toolchain must use the minimal profile"
    );

    let lockfile =
        fs::read_to_string(workspace_file("Cargo.lock")).expect("workspace must track Cargo.lock");
    assert!(
        lockfile.starts_with("# This file is automatically @generated by Cargo."),
        "Cargo.lock must be a Cargo-generated lockfile"
    );
}

#[test]
fn workspace_features_are_explicitly_opt_in() {
    let policy = fs::read_to_string(workspace_file("FEATURES.md"))
        .expect("workspace must document feature policy");
    assert!(policy.contains("default = []"));
    assert!(policy.contains("must be additive"));

    for package in [
        "yeokcham-cli",
        "yeokcham-core",
        "yeokcham-daemon",
        "yeokcham-ffi",
        "yeokcham-protocol",
        "yeokcham-relay",
    ] {
        let manifest = fs::read_to_string(workspace_file(&format!("crates/{package}/Cargo.toml")))
            .expect("workspace crate must include Cargo.toml");
        assert!(
            manifest.contains("[features]\ndefault = []"),
            "{package} must keep all features opt-in"
        );
    }
}

#[test]
fn ci_audits_dependencies_on_every_change_and_weekly() {
    let workflow = fs::read_to_string(workspace_file(".github/workflows/ci.yml"))
        .expect("workspace must include CI workflow");
    assert!(workflow.contains("schedule:"));
    assert!(workflow.contains("cron: \"17 3 * * 1\""));
    assert!(workflow.contains("  audit:\n    runs-on: ubuntu-latest"));
    assert!(workflow.contains("cargo install cargo-audit --version 0.22.2 --locked"));
    assert!(workflow.contains("cargo audit --deny warnings --ignore RUSTSEC-2024-0436"));
}

#[test]
fn pins_and_audits_cryptographic_dependencies() {
    let manifest = fs::read_to_string(workspace_file("Cargo.toml"))
        .expect("workspace must include Cargo.toml");
    for dependency in [
        "argon2 = { version = \"=0.5.3\"",
        "chacha20poly1305 = { version = \"=0.11.0\"",
        "ed25519-dalek = { version = \"=3.0.0\"",
        "getrandom = { version = \"=0.4.3\"",
        "hkdf = { version = \"=0.13.0\"",
        "sha2 = { version = \"=0.11.0\"",
        "subtle = \"=2.6.1\"",
        "x25519-dalek = { version = \"=3.0.0\"",
        "zeroize = { version = \"=1.9.0\"",
    ] {
        assert!(
            manifest.contains(dependency),
            "cryptographic dependency must be exact-pinned: {dependency}"
        );
    }

    let policy = fs::read_to_string(workspace_file("deny.toml"))
        .expect("workspace must include dependency policy");
    assert!(policy.contains("[advisories]"));
    assert!(policy.contains("RUSTSEC-2024-0436"));
    assert!(policy.contains("unknown-registry = \"deny\""));
    assert!(policy.contains("unknown-git = \"deny\""));

    let workflow = fs::read_to_string(workspace_file(".github/workflows/ci.yml"))
        .expect("workspace must include CI workflow");
    assert!(workflow.contains("  dependency-policy:\n    runs-on: ubuntu-latest"));
    assert!(workflow.contains("command-arguments: advisories sources"));
}

#[test]
fn ci_enforces_the_dependency_license_allowlist() {
    let policy = fs::read_to_string(workspace_file("deny.toml"))
        .expect("workspace must include dependency policy");
    for license in ["Apache-2.0", "BlueOak-1.0.0", "MIT", "Unicode-3.0"] {
        assert!(
            policy.contains(license),
            "license policy must allow {license}"
        );
    }
    assert!(policy.contains("confidence-threshold = 0.8"));

    let workflow = fs::read_to_string(workspace_file(".github/workflows/ci.yml"))
        .expect("workspace must include CI workflow");
    assert!(workflow.contains("  licenses:\n    runs-on: ubuntu-latest"));
    assert!(
        workflow
            .contains("EmbarkStudios/cargo-deny-action@3c6349835b2b7b196a839186cb8b78e02f7b5f25")
    );
    assert!(workflow.contains("command-arguments: licenses"));
}
